version: '2'

vars:
  BUILD_DIR: build
  BINARY: fta_app
  LDFLAGS: -ldflags "-w -s -X main.buildAt={{now | date "2006-01-02T15:04:05Z07:00"}}"

tasks:
  build:
    desc: Build the go binary for current platform.
    cmds:
      - cd cmd/{{.BINARY}} && go build -o ../../{{.BUILD_DIR}}/{{.BINARY}}{{exeExt}} {{.LDFLAGS}} -v .

  run:
    desc: Run the program
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY}}{{exeExt}}

  linux:
    desc: Build the go binary for Linux.
    cmds:
      - cd cmd/{{.BINARY}} && GOOS=linux GOARCH=amd64 go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/linux/{{.BINARY}} -v .